### ISSUE TITLE
Does this implementation guarantee single root?

### ISSUE THREAD

**Issue by speedcell4** [andersjo/dependency_decoding#1]
This implementation may decode a maximum spanning **forest** instead of a **tree**?

for example,

```python3
import numpy as np
from dependency_decoding import chu_liu_edmonds

np.random.seed(45)
score_matrix = np.random.rand(4, 4)
heads, tree_score = chu_liu_edmonds(score_matrix)
print(heads, tree_score)

# Output: [-1, 0, 3, 0] 2.0852936018171557
```

as you have mentioned in `README.md`,

> including the artificial root node

so the first `-1` means this is the artificial root node, then the following two `0`s means that two nodes depend on this artificial root node. If I want to add a constraint that only one node can depend on the artificial root node, how can I do this?

**Comment by speedcell4** [comment]
problem solved, thanks anyway

**Comment by ghost** [comment]
@speedcell4 Could you maybe share your solution for this? Thank you in advance.
